world_model:
  name: ctrlworld
  checkpoint_path: checkpoints/wm/ctrlworld/checkpoint-10000.pt
  params:
    svd_model_path: external/stable-video-diffusion-img2vid
    clip_model_path: external/clip-vit-base-patch32
    debug: false
    debug_log_limit: 3
    num_frames: 5
    num_history: 6
    action_dim: 7
    action_downsample: 3
    width: 320
    height: 192
    num_inference_steps: 50
    decode_to_rgb: true

policy:
  name: molmoact2
  checkpoint_path: allenai/MolmoAct2-DROID
  params:
    dtype: bfloat16
    device: cuda
    norm_tag: franka_droid
    action_mode: continuous
    num_steps: 10
    exterior_view_name: exterior_left
    wrist_view_name: wrist
    stacked_view_order: [exterior_left, exterior_right, wrist]
    enable_depth_reasoning: false
    normalize_language: true
    enable_cuda_graph: false
    joint_position_dim: 7
    debug: false
    debug_log_limit: 3

reward_model:
  name: dummy
  params: {}

scheduler:
  chunk_size: 15

duration: 30
action_hz: 15
video_dir: outputs/roboarena/base_wm/irom_towel/molmoact2_droid
dataset_path: data/benchmark/irom_towel_fold
